format = "$directory$git_branch"
right_format = "$status$cmd_duration$battery$time$os$username$hostname "
add_newline = false

[line_break]
disabled = true

[character]
format = "╰─$symbol"
success_symbol = "→"
error_symbol = "×"
disabled = false

[fill]
symbol = "-"
style = "fg:bright-black"

[status]
format = "[ status: $status](fg:red)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[exit: $pipestatus](fg:red)"
disabled = false

[directory]
format = "[ dir: $read_only$truncation_symbol$path](fg:blue)"
home_symbol = "~"
truncation_symbol = "../"
truncation_length = 3
read_only = "RO "
read_only_style = "fg:red"

[directory.substitutions]
Desktop = "desk"
Documents = "docs"
Downloads = "dls"
Music = "music"
Pictures = "pics"
Videos = "vids"
config = "cfg"

[git_branch]
symbol = ""
format = "[ branch: $branch ](fg:green)"
only_attached = false

[git_commit]
tag_symbol = " tag:"


