format = "$directory$git_branch$git_status"
right_format = "$status$cmd_duration$battery$time$os$username$hostname"
add_newline = false

[line_break]
disabled = true

[character]
format = "╰─$symbol"
success_symbol = "→"
error_symbol = "×"
disabled = false

[fill]
symbol = "-"
style = "fg:bright-black"

[status]
format = "[ status: $status](fg:red)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[exit: $pipestatus](fg:red)"
disabled = false

[directory]
format = "[ dir: $read_only$truncation_symbol$path](fg:blue)"
home_symbol = "~"
truncation_symbol = "../"
truncation_length = 3
read_only = "RO "
read_only_style = "fg:red"

[directory.substitutions]
Desktop = "Desk"
Documents = "Docs"
Downloads = "Dls"
Music = "Music"
Pictures = "Pics"
Videos = "Vids"
dev = "Dev"
config = "Cfg"

[git_branch]
symbol = ""
format = "[ branch: $branch](fg:green)"
only_attached = false

[git_commit]
tag_symbol = " tag:"

[git_status]
format = "[ git: $all_status](fg:yellow)"
conflicted = "conflicted($count) "
untracked = "untracked($count) "
stashed = "stash($count) "
modified = "mod($count) "
staged = "staged($count) "
renamed = "renamed($count) "
deleted = "deleted($count) "
ahead = "↑$count "
diverged = "⇡$ahead_count⇣$behind_count "
behind = "↓$count "

[battery]
format = "[battery: $percentage](fg:yellow)"
display = [
  { threshold = 25, style = "bold yellow" },
  { threshold = 10, style = "bold red" }
]

[cmd_duration]
min_time = 500
format = "[took: $duration](fg:cyan)"

[time]
format = "[time: $time](fg:magenta)"
time_format = "%I:%M %p"
disabled = false

[username]
format = "[user: $user](fg:white)"
show_always = true

[hostname]
format = "[host: $hostname](fg:white)"
ssh_symbol = "(ssh)"
ssh_only = false

